  %YAML:1.0
  # data
  # the tum dataset directory, change it to yours!
  #dataset_dir: /home/xiang/dataset/rgbd_dataset_freiburg1_desk

  # camera intrinsics
  # fr1
  camera.fx: 517.3
  camera.fy: 516.5
  camera.cx: 325.1
  camera.cy: 249.7

  # init camera pose
  init.x: 0
  init.y: 0
  init.z: 1.7
  init.qx: -0,7071
  init.qy: 0
  init.qz: 0
  init.qw: 0.7071